v12.0.1
New release is required because v12.0.0 is broken on pypi:

    Error: No such command 'ui'.

See: https://discuss.overhang.io/t/error-no-such-command-ui/1837